[theme]
base = "dark"
primaryColor = "#22d3ee"
backgroundColor = "#03101a"
secondaryBackgroundColor = "#0a2436"
textColor = "#e6f7ff"
font = "sans serif"

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
